
const DATA=JSON.parse(document.getElementById('gameData').textContent);
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const SAVE='jion_game_v3';
const defaultState={season:1,gold:{1:1000000,2:1000000000},points:0,revival:0,shield:{1:0,2:0},tears:{1:0,2:50},pity:{1:0,2:0},level:{1:1,2:1},max:{1:1,2:1},attempts:0,successes:0,failures:0,destroys:0,critical:0,sells:0,warps:0,earnedPoints:0,titles:['칭호 없음'],title:'칭호 없음',achievements:[],log:[]};
let S=load(); let scene,renderer,camera,object,clock,animId;
function load(){try{const x=JSON.parse(localStorage.getItem(SAVE)); return x?deepMerge(structuredClone(defaultState),x):structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function deepMerge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=deepMerge(a[k]||{},b[k]);else a[k]=b[k]}return a}
function save(){localStorage.setItem(SAVE,JSON.stringify(S))}
function fmt(n){if(!Number.isFinite(n))return '∞'; if(n<1000)return Math.floor(n).toLocaleString('ko-KR'); const units=['','만','억','조','경','해','자']; let u=0,x=n; while(x>=10000&&u<units.length-1){x/=10000;u++} return u?`${x>=100?Math.floor(x):x>=10?x.toFixed(1):x.toFixed(2)}${units[u]}`:Math.floor(n).toLocaleString('ko-KR')}
function data(){return DATA.smell[String(S.season)][String(S.level[S.season])]||DATA.smell[String(S.season)]['0']}
function maxLv(){return S.season===1?35:25}
function prob(){const p=DATA.prob[String(S.season)][String(S.level[S.season])];return p||[5,40,50,5]}
function cost(){return (S.season===1?DATA.cost1:DATA.cost2)[S.level[S.season]]||0}
function log(msg,type=''){S.log.unshift({t:new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}),m:msg,type});S.log=S.log.slice(0,30);renderLog()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.style.opacity=1;t.style.transform='translateX(-50%) translateY(0)';clearTimeout(window._toast);window._toast=setTimeout(()=>{t.style.opacity=0;t.style.transform='translateX(-50%) translateY(-15px)'},1700)}
function unlock(id){if(!S.achievements.includes(id)){S.achievements.push(id);const a=DATA.achievements[id];if(a){S.gold[S.season]+=a.reward||0; if(a.title&&!S.titles.includes(a.title))S.titles.push(a.title);toast(`🏆 업적 달성: ${a.name}`);log(`업적 달성 — ${a.name} (+${fmt(a.reward||0)}G)`,'good')}}}
function checkAchievements(){if(S.attempts>=1)unlock('first_enhance');if(S.level[1]>=5)unlock('level_5');if(S.level[1]>=10)unlock('level_10');if(S.level[1]>=15)unlock('level_15');if(S.level[1]>=20)unlock('level_20');if(S.level[1]>=25)unlock('level_25');if(S.level[1]>=30)unlock('level_30');if(S.level[1]>=35)unlock('level_35');if(S.season===2)unlock('rebirth');if(S.level[2]>=5)unlock('s2_level_5');if(S.level[2]>=10)unlock('s2_level_10');if(S.level[2]>=15)unlock('s2_level_15');if(S.level[2]>=20)unlock('s2_level_20');if(S.level[2]>=25)unlock('s2_level_25');if(S.attempts>=50)unlock('enhance_50');if(S.attempts>=100)unlock('enhance_100');if(S.attempts>=200)unlock('enhance_200');if(S.critical>=1)unlock('critical');if(S.critical>=5)unlock('critical_5');if(S.sells>=1)unlock('seller');if(S.sells>=10)unlock('seller_10');if(S.gold[S.season]>=1e9)unlock('rich');if(S.earnedPoints>=100000)unlock('points_100k');if(S.earnedPoints>=1000000)unlock('points_1m')}
function enhance(){const lv=S.level[S.season], mx=maxLv();if(lv>=mx){toast('최종 단계입니다!');return}const c=cost();if(S.gold[S.season]<c){toast('GOLD가 부족합니다');log('강화 실패 — GOLD 부족','bad');return}S.gold[S.season]-=c;S.attempts++;let [sp,down,destroy,hold]=prob();let status='HOLD',msg='강화가 유지되었습니다.';if(S.pity[S.season]>=3){sp=100;down=destroy=hold=0;status='PITY_SUCCESS'}else{const r=Math.random()*100;if(r<sp)status=Math.random()<.05&&lv+2<=mx?'CRITICAL':'SUCCESS';else if(r<sp+down)status='FAILED';else if(r<sp+down+destroy)status='DESTROYED';else status='HOLD'}
if(status==='SUCCESS'){S.level[S.season]++;S.max[S.season]=Math.max(S.max[S.season],S.level[S.season]);S.pity[S.season]=0;S.successes++;msg=`강화 성공! ${S.level[S.season]-1} → ${S.level[S.season]}`;givePoints(S.level[S.season]);unlockWarp();}
else if(status==='CRITICAL'){S.level[S.season]+=2;S.max[S.season]=Math.max(S.max[S.season],S.level[S.season]);S.pity[S.season]=0;S.successes++;S.critical++;msg=`⚡ 크리티컬! ${S.level[S.season]-2} → ${S.level[S.season]}`;givePoints(S.level[S.season]);unlockWarp()}
else if(status==='PITY_SUCCESS'){S.level[S.season]++;S.max[S.season]=Math.max(S.max[S.season],S.level[S.season]);S.pity[S.season]=0;msg=`✨ PITY 발동! ${S.level[S.season]-1} → ${S.level[S.season]}`;givePoints(S.level[S.season]);unlockWarp()}
else if(status==='FAILED'){S.pity[S.season]=Math.min(3,S.pity[S.season]+1);S.level[S.season]=Math.max(1,lv-1);S.failures++;S.tears[S.season]=Math.min(60,S.tears[S.season]+1);msg=`강화 실패… ${lv} → ${S.level[S.season]}`}
else if(status==='DESTROYED'){if(S.shield[S.season]>0){S.shield[S.season]--;S.pity[S.season]=Math.min(3,S.pity[S.season]+1);S.failures++;S.tears[S.season]=Math.min(60,S.tears[S.season]+1);status='SHIELD_SAVED';msg='💥 파괴 위기! 방지권이 사용되었습니다.'}else if(S.revival>0){showRevive(lv);return}else{S.pity[S.season]=Math.min(3,S.pity[S.season]+1);S.level[S.season]=1;S.failures++;S.destroys++;S.tears[S.season]=Math.min(60,S.tears[S.season]+2);msg='💥 파괴되었습니다. 1단계로 돌아갑니다.'}}
else{S.pity[S.season]=Math.min(3,S.pity[S.season]+1);S.failures++;S.tears[S.season]=Math.min(60,S.tears[S.season]+1);msg='강화가 유지되었습니다.'}
S._status=status;log(msg,status==='SUCCESS'||status==='CRITICAL'||status==='PITY_SUCCESS'?'good':status==='DESTROYED'?'bad':'');checkAchievements();save();render();flash(status)}
function givePoints(lv){const p=DATA.points[String(lv)]||0;S.points+=p;S.earnedPoints+=p}
function unlockWarp(){}
function showRevive(lost){openModal(`<button class="modal-close" onclick="closeModal()">닫기</button><h2>💥 파괴 발생</h2><p>${lost}단계가 파괴되었습니다.</p><div class="buy-row"><div><b>부활권을 사용하시겠습니까?</b><small>사용하면 파괴 직전 단계로 복구됩니다.<br>보유 부활권: ${S.revival}장</small></div><button onclick="useRevival(${lost})">O 사용</button></div><div class="buy-row"><div><b>사용하지 않기</b></div><button onclick="destroyWithoutRevive(${lost})">X</button></div>`)}
function useRevival(lv){if(S.revival<=0){toast('부활권이 없습니다');return}S.revival--;S.level[S.season]=lv;S._status='REVIVED';closeModal();log(`🧿 부활권 사용 — ${lv}단계 복구`,'good');save();render();flash('REVIVED')}
function destroyWithoutRevive(lv){S.pity[S.season]=Math.min(3,S.pity[S.season]+1);S.level[S.season]=1;S.failures++;S.destroys++;S.tears[S.season]=Math.min(60,S.tears[S.season]+2);closeModal();log('💥 파괴 — 1단계로 초기화','bad');save();render();flash('DESTROYED')}
function sell(){const lv=S.level[S.season];if(lv<=1){toast('판매할 단계가 없습니다');return}const v=DATA.smell[String(S.season)][String(lv)].price||0;S.gold[S.season]+=v;S.level[S.season]=1;S.sells++;S._status='SOLD';log(`💰 ${lv}단계 판매 +${fmt(v)}G`,'good');checkAchievements();save();render()}
function buyRevival(){const price=5000000;if(S.gold[S.season]<price){toast('GOLD 부족');return}S.gold[S.season]-=price;S.revival++;toast('🧿 부활권 1장 구매');log('부활권 1장 구매','good');save();render()}
function buyShield(){const price=Math.max(50000,cost()*15);if(S.points<price){toast('POINT 부족');return}S.points-=price;S.shield[S.season]++;toast('🛡️ 방지권 구매');save();render()}
function warp(){const lv=parseInt(prompt('이동할 단계 번호를 입력하세요. (이미 도달한 단계만 가능)')||'');if(!lv||lv<1||lv>S.max[S.season]||lv>maxLv()){toast('워프할 수 없는 단계입니다');return}S.level[S.season]=lv;S._status='WARP';S.warps++;log(`🚀 ${lv}단계로 워프`,'good');save();render()}
function render(){const d=data(),lv=S.level[S.season],mx=maxLv(),p=prob();$('#gold').textContent=fmt(S.gold[S.season]);$('#points').textContent=fmt(S.points)+' P';$('#max').textContent='Lv. '+S.max[S.season];$('#titleText').textContent=S.title;$('#progressText').textContent=`${lv} / ${mx}`;$('#progressBar').style.width=((lv-1)/(mx-1)*100)+'%';$('#levelName').textContent=d.name;$('#levelDesc').textContent=d.desc;$('#rarity').textContent='TIER '+d.tier;$('#stageEyebrow').textContent=`SEASON 0${S.season} • ENHANCEMENT`;$('#stageBadge').textContent='LV. '+lv;$('#currentLv').textContent='LV. '+lv;$('#targetLv').textContent=lv>=mx?'MAX':'LV. '+(lv+1);$('#nextName').textContent=lv>=mx?'MAX LEVEL':(DATA.smell[String(S.season)][String(lv+1)]?.name||'NEXT');$('#nextBar').style.width=(lv>=mx?100:Math.min(100,(lv/(mx))*100))+'%';$('#pSuccess').textContent=p[0]+'%';$('#pDown').textContent=p[1]+'%';$('#pDestroy').textContent=p[2]+'%';$('#pHold').textContent=p[3]+'%';$('#chance').textContent=p[0]+'%';$('#cost').textContent=lv>=mx?'MAX':' '+fmt(cost())+' GOLD';$('#shield').textContent=S.shield[S.season];$('#tears').textContent=`${S.tears[S.season]} / 60` ;$('#revival').textContent=S.revival;$('#pity').textContent=`${S.pity[S.season]} / 4` ;$('#status').textContent=S._status||'READY';$('#enhanceBtn').disabled=lv>=mx; $$('.season').forEach(b=>b.classList.toggle('active',+b.dataset.season===S.season));renderLevels();renderLog();updateShape()}
function renderLevels(){const box=$('#levelList'),mx=maxLv(),lv=S.level[S.season];box.innerHTML='';for(let i=1;i<=mx;i++){const el=document.createElement('div');el.className='level-item '+(i<lv?'done unlocked ':'')+(i===lv?'current ':'')+(i<=S.max[S.season]?'unlocked':'');el.innerHTML=`<span class="num">${i}</span><span>${i===mx?'★ FINAL':'LEVEL '+String(i).padStart(2,'0')}</span>`;el.onclick=()=>{if(i<=S.max[S.season]){S.level[S.season]=i;save();render()}};box.appendChild(el)}}
function renderLog(){const box=$('#log');box.innerHTML=(S.log.length?S.log:[{t:'--:--:--',m:'게임에 입장했습니다.',type:''}]).slice(0,18).map(x=>`<div class="log-line"><span>${x.t}</span> <strong>${x.m}</strong></div>`).join('')}
function flash(status){const el=$('#scene');el.classList.remove('result-flash');void el.offsetWidth;el.classList.add('result-flash');toast(({SUCCESS:'✨ 강화 성공!',CRITICAL:'⚡ 크리티컬 성공!',PITY_SUCCESS:'🛡️ PITY 성공!',FAILED:'강화 실패…',DESTROYED:'💥 파괴!',SHIELD_SAVED:'🛡️ 방지권 발동!',REVIVED:'🧿 부활 성공!',WARP:'🚀 워프 완료!'}[status]||'강화 완료'))}
function openModal(content){$('#modal').innerHTML=content;$('#modalLayer').classList.remove('hidden')}function closeModal(){$('#modalLayer').classList.add('hidden')}
function shop(){openModal(`<button class="modal-close" onclick="closeModal()">닫기</button><h2>🛒 아이템 상점</h2><p>강화를 안정적으로 진행하기 위한 아이템입니다.</p><div class="buy-row"><div><b>🧿 부활권</b><small>파괴 시 파괴 직전 단계로 부활</small></div><button onclick="buyRevival()">5,000,000 G</button></div><div class="buy-row"><div><b>🛡️ 방지권</b><small>파괴 판정 1회를 막습니다.</small></div><button onclick="buyShield();closeModal()">POINT 구매</button></div>`)}
function achievements(){const all=Object.entries(DATA.achievements);openModal(`<button class="modal-close" onclick="closeModal()">닫기</button><h2>🏆 업적</h2><p>${S.achievements.length} / ${all.length} 달성</p><div class="modal-grid">${all.map(([id,a])=>`<div class="modal-item"><b>${S.achievements.includes(id)?'✅':'🔒'} ${a.name}</b><small>${a.desc}<br>보상 ${fmt(a.reward||0)}G · 칭호 ${a.title||'-'}</small></div>`).join('')}</div>`)}
function titles(){openModal(`<button class="modal-close" onclick="closeModal()">닫기</button><h2>✦ 칭호 컬렉션</h2><p>획득한 칭호를 선택하세요.</p><div class="modal-grid">${S.titles.map(t=>{const th=DATA.themes[t]||['#fff','#777','#111','✦'];return `<div class="modal-item" style="border-color:${th[0]}55"><b>${th[3]} ${t}</b><small style="color:${th[0]}">${t===S.title?'현재 장착 중':'보유 칭호'}</small><br><button onclick="equipTitle(${JSON.stringify(t)})" style="margin-top:7px;padding:6px 9px;border-radius:7px;background:${th[0]};color:#08101b;font-size:9px;font-weight:900">장착</button></div>`}).join('')}</div>`)}
function equipTitle(t){S.title=t;save();titles();render()}
function stats(){openModal(`<button class="modal-close" onclick="closeModal()">닫기</button><h2>📊 플레이 기록</h2><div class="modal-grid">${[['강화 시도',S.attempts],['성공',S.successes],['실패',S.failures],['파괴',S.destroys],['크리티컬',S.critical],['판매',S.sells],['워프',S.warps],['획득 POINT',S.earnedPoints]].map(x=>`<div class="modal-item"><b>${x[0]}</b><small>${fmt(x[1])}</small></div>`).join('')}</div>`)}
function updateShape(){if(!window.THREE||!renderer)return;const lv=S.level[S.season];if(object)scene.remove(object);object=new THREE.Group();const color=data().color||'#42d9ff';const mat=new THREE.MeshStandardMaterial({color,metalness:.65,roughness:.22,emissive:new THREE.Color(color),emissiveIntensity:.12});const wire=new THREE.MeshBasicMaterial({color,wireframe:true,transparent:true,opacity:.12});
const G=THREE;let geo;const n=lv-1;
const factories=[()=>new G.IcosahedronGeometry(1.65,1),()=>new G.OctahedronGeometry(1.8,1),()=>new G.TetrahedronGeometry(1.95,1),()=>new G.DodecahedronGeometry(1.55,1),()=>new G.TorusGeometry(1.25,.38,16,48),()=>new G.TorusKnotGeometry(1.15,.35,96,16,2,3),()=>new G.SphereGeometry(1.65,24,16),()=>new G.CapsuleGeometry(1,1.3,8,20),()=>new G.ConeGeometry(1.55,2.9,7),()=>new G.CylinderGeometry(1.35,1.35,2.6,8),()=>new G.CylinderGeometry(1.1,1.55,2.8,6),()=>new G.BoxGeometry(2.35,2.35,2.35),()=>new G.OctahedronGeometry(1.6,2),()=>new G.IcosahedronGeometry(1.6,2),()=>new G.TorusGeometry(1.5,.22,8,64),()=>new G.TorusKnotGeometry(1.2,.27,128,12,3,5),()=>new G.ConeGeometry(1.5,2.8,12),()=>new G.CylinderGeometry(.55,1.6,2.8,12),()=>new G.SphereGeometry(1.7,12,8),()=>new G.BoxGeometry(2.7,1.35,1.35),()=>new G.CylinderGeometry(1.4,1.4,2.2,20),()=>new G.TorusGeometry(1.15,.48,24,32),()=>new G.DodecahedronGeometry(1.7,0),()=>new G.IcosahedronGeometry(1.75,0),()=>new G.OctahedronGeometry(1.9,0),()=>new G.TetrahedronGeometry(2.1,0),()=>new G.ConeGeometry(1.65,2.7,5),()=>new G.CylinderGeometry(1.45,.7,2.8,5),()=>new G.CylinderGeometry(.7,1.45,2.8,5),()=>new G.TorusKnotGeometry(1.1,.32,80,8,2,5),()=>new G.TorusKnotGeometry(1.1,.32,80,8,3,4),()=>new G.TorusGeometry(1.45,.18,6,30),()=>new G.TorusGeometry(1.2,.55,10,24),()=>new G.SphereGeometry(1.75,32,10),()=>new G.SphereGeometry(1.45,10,32),()=>new G.BoxGeometry(2.5,1.4,1.4),()=>new G.BoxGeometry(1.4,2.5,1.4),()=>new G.BoxGeometry(1.4,1.4,2.5),()=>new G.ConeGeometry(1.3,3.1,16),()=>new G.CylinderGeometry(1.15,1.55,3,16),()=>new G.TorusKnotGeometry(1.25,.22,100,10,2,7),()=>new G.TorusKnotGeometry(1.25,.22,100,10,3,7),()=>new G.IcosahedronGeometry(1.65,3),()=>new G.OctahedronGeometry(1.75,3),()=>new G.DodecahedronGeometry(1.6,1),()=>new G.TetrahedronGeometry(2,2),()=>new G.TorusGeometry(1.35,.3,30,50),()=>new G.CylinderGeometry(1.4,1.4,2.5,32),()=>new G.CapsuleGeometry(.75,1.8,12,32),()=>new G.ConeGeometry(1.6,2.9,32),()=>new G.BoxGeometry(2.2,2.2,2.2,4,4,4),()=>new G.SphereGeometry(1.6,48,24),()=>new G.TorusKnotGeometry(1.1,.4,160,20,2,3),()=>new G.TorusGeometry(1.55,.12,8,80),()=>new G.IcosahedronGeometry(1.8,2),()=>new G.DodecahedronGeometry(1.8,1),()=>new G.CylinderGeometry(1.5,1.5,2.7,10)];geo=factories[n%factories.length]();let mesh=new G.Mesh(geo,mat);mesh.castShadow=true;object.add(mesh);let wm=new G.Mesh(geo,wire);object.add(wm);object.rotation.set(.25,.4,0);object.userData.base=lv;object.userData.color=color;scene.add(object);}
function init3D(){if(!window.THREE){$('#fallbackShape').style.display='grid';return}const root=$('#threeRoot');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(38,root.clientWidth/root.clientHeight,.1,100);camera.position.set(0,1.1,7);renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(root.clientWidth,root.clientHeight);renderer.domElement.className='three-canvas';root.appendChild(renderer.domElement);const amb=new THREE.AmbientLight(0xffffff,.65);scene.add(amb);const l1=new THREE.PointLight(0x75ddff,18,12);l1.position.set(3,4,4);scene.add(l1);const l2=new THREE.PointLight(0x9b6cff,12,10);l2.position.set(-4,1,2);scene.add(l2);clock=new THREE.Clock();function tick(){const t=clock.getElapsedTime();if(object){object.rotation.y=t*.42;object.rotation.x=Math.sin(t*.55)*.16;object.position.y=Math.sin(t*1.3)*.08}renderer.render(scene,camera);animId=requestAnimationFrame(tick)}tick();new ResizeObserver(()=>{if(root.clientWidth&&root.clientHeight){camera.aspect=root.clientWidth/root.clientHeight;camera.updateProjectionMatrix();renderer.setSize(root.clientWidth,root.clientHeight)}}).observe(root);updateShape()}
$$('.season').forEach(b=>b.onclick=()=>{S.season=+b.dataset.season;S._status='READY';save();render();log(`SEASON 0${S.season} 진입`)});$('#enhanceBtn').onclick=enhance;$('#sellBtn').onclick=sell;$('#warpBtn').onclick=warp;$('#reviveShopBtn').onclick=buyRevival;$('#resetBtn').onclick=()=>{if(confirm('모든 게임 기록을 초기화할까요?')){localStorage.removeItem(SAVE);S=load();location.reload()}};$$('[data-modal="shop"]').forEach(b=>b.onclick=shop);$$('[data-modal="achievements"]').forEach(b=>b.onclick=achievements);$$('[data-modal="titles"]').forEach(b=>b.onclick=titles);$$('[data-modal="stats"]').forEach(b=>b.onclick=stats);$('#modalLayer').onclick=e=>{if(e.target.id==='modalLayer')closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!$('#enhanceBtn').disabled&&!document.querySelector('.modal-layer:not(.hidden)'))enhance()});
window.closeModal=closeModal;window.useRevival=useRevival;window.destroyWithoutRevive=destroyWithoutRevive;window.buyRevival=buyRevival;window.buyShield=buyShield;window.equipTitle=equipTitle;
window.addEventListener('load',()=>{setTimeout(()=>{$('#boot').classList.add('hidden');$('#app').classList.remove('hidden');init3D();render();log('게임 데이터 로드 완료','good')},450)});
